webapp/scout/scout/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('users.urls', namespace='users', app_name='users')),
]

webapp/scout/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.index, name='index'),
    url(r"^cadastro$", views.cadastro, name='cadastro'),
    url(r"^login$", views.do_login, name='login'),
    url(r"^logout$", views.do_logout, name='logout'),
]

webapp/scout/users/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

webapp/scout/users/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User

class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'maxlength': 255}),
        }

        error_messages = {
            'first_name': {
                'required': 'Este campo é obrigatório'
            },
            'last_name': {
                'required': 'Este campo é obrigatório'
            },
            'email': {
                'required': 'Entre com um email válido'
            },
            'username': {
                'required': 'Este campo é obrigatório'
            },
            'password': {
                'required': 'Este campo é obrigatório'
            },
        }

webapp/scout/users/views.py
from django.shortcuts import render, redirect
from users.forms import UserModelForm
from django.http import HttpResponse
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def index(request):
    return HttpResponse("Base")

#@login_required
def cadastro(request):
    form = UserModelForm(request.POST or None)
    context = {'form':form}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/cadastro')
    return render(request, 'users/cadastro.html', context)

def do_login(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect('/cadastro')
    return render(request, 'users/login.html')

def do_logout(request):
    logout(request)
    return redirect('/login')

webapp/scout/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="SCOUT">
    <meta name="author" content="Cleiton">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>

  <body>

    <div class="container">
        {% block content %}
        {% endblock %}

    </div> <!-- /container -->
  </body>
</html>

webapp/scout/users/templates/users/cadastro.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'users:cadastro' %}" class="form-signin" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Please sign in</h2>
    <div class="row">
        <label> First Name </label>
        {{ form.first_name }}
        {{ form.first_name.errors }}
    </div>
    <div class="row">
        <label> Last Name </label>
        {{ form.last_name }}
        {{ form.last_name.errors }}
    </div>
    <div class="row">
        <label> Email </label>
        {{ form.email}}
        {{ form.email.errors }}
    </div>
    <div class="row">
        <label> Username </label>
        {{ form.username}}
        {{ form.username.errors }}
    </div>
    <div class="row">
        <label> Password </label>
        {{ form.password}}
        {{ form.password.errors }}
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
</form>
{% endblock %}

webapp/scout/users/templates/users/jogo.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'users:logout' %}">Logout</a>
{% endblock %}

webapp/scout/users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'users:login' %}" class="form-signin" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Login</h2>

    <div class="form-group">
        <div class="col-md-4">
            <input type="text" name="username" class="form-control" placeholder="Login">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-4">
            <input type="password" name="password" class="form-control" placeholder="Senha">
        </div>
    </div>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
</form>
{% endblock %}